/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewAcademia;

import ClassesAcademia.Exercicio;

/**
 *
 * @author João
 */
public class CadastroExercicio extends javax.swing.JFrame {

    private TelaPrincipal telaPrincipal;
    
    public CadastroExercicio(TelaPrincipal telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbExercicio = new javax.swing.JLabel();
        lbRepeticao = new javax.swing.JLabel();
        lbSeries = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfExercicio = new javax.swing.JTextField();
        tfRepeticao = new javax.swing.JTextField();
        tfSerie = new javax.swing.JTextField();
        tfDescricao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lbTipoTreino = new javax.swing.JLabel();
        cbTipoTreino = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Treinos");

        lbExercicio.setText("Exercício:");

        lbRepeticao.setText("Repetição:");

        lbSeries.setText("Séries:");

        jLabel1.setText("Descrição:");

        btnSalvar.setText("Adicionar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lbTipoTreino.setText("Tipo de Treino:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRepeticao)
                                    .addComponent(lbExercicio)
                                    .addComponent(lbSeries)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTipoTreino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfDescricao)
                            .addComponent(tfSerie, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfExercicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(tfRepeticao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoTreino, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoTreino)
                    .addComponent(cbTipoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbExercicio)
                    .addComponent(tfExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRepeticao)
                    .addComponent(tfRepeticao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSeries)
                    .addComponent(tfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String exercicio = tfExercicio.getText();
        String repeticao = tfRepeticao.getText();
        String serie = tfSerie.getText();
        String descricao = tfDescricao.getText();
//                int codigo = Integer.parseInt(tfCodigo.getText());
//        String nome = tfNome.getText();
//        Categoria cat = new Categoria(codigo, nome);
//        this.sistemaView.getCategorias().add(cat);
        //Treino treino = new Treino(exercicio, repeticao, serie, descricao);
        //this.telaPrincipal.getTreino().add(treino);
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbTipoTreino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbExercicio;
    private javax.swing.JLabel lbRepeticao;
    private javax.swing.JLabel lbSeries;
    private javax.swing.JLabel lbTipoTreino;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfExercicio;
    private javax.swing.JTextField tfRepeticao;
    private javax.swing.JTextField tfSerie;
    // End of variables declaration//GEN-END:variables
}
