/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewAcademia;

import ClassesAcademia.Aluno;
import ClassesAcademia.Exercicio;
import java.util.ArrayList;

/**
 *
 * @author João
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private ArrayList<Aluno> aluno;
    
    public TelaPrincipal() {
//        this.categorias = new ArrayList<Categoria>();
//        this.produtos = new ArrayList<Produto>();
        this.aluno = new ArrayList<Aluno>();

        initComponents();
    }

    
    public ArrayList<Aluno> getAluno(){
        return this.aluno;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAluno = new javax.swing.JButton();
        btnTreino = new javax.swing.JButton();
        mbMenu = new javax.swing.JMenuBar();
        mnAluno = new javax.swing.JMenu();
        miAlunos = new javax.swing.JMenuItem();
        mnTreino = new javax.swing.JMenu();
        miTreinos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        btnAluno.setText("Cadastrar Aluno");
        btnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoActionPerformed(evt);
            }
        });

        btnTreino.setText("Cadastrar Treino");
        btnTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreinoActionPerformed(evt);
            }
        });

        mnAluno.setText("Alunos");

        miAlunos.setText("Relatório Alunos");
        miAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAlunosActionPerformed(evt);
            }
        });
        mnAluno.add(miAlunos);

        mbMenu.add(mnAluno);

        mnTreino.setText("Treinos");

        miTreinos.setText("Tipos de Treinos");
        miTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTreinosActionPerformed(evt);
            }
        });
        mnTreino.add(miTreinos);

        mbMenu.add(mnTreino);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTreino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnAluno)
                .addGap(26, 26, 26)
                .addComponent(btnTreino)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoActionPerformed
        CadastroAluno cadAluno = new CadastroAluno(this);
        cadAluno.setVisible(true);
    }//GEN-LAST:event_btnAlunoActionPerformed

    private void btnTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreinoActionPerformed
        CadastroExercicio cadTreino = new CadastroExercicio(this);
        cadTreino.setVisible(true);
    }//GEN-LAST:event_btnTreinoActionPerformed

    private void miAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAlunosActionPerformed
        Alunos alunos = new Alunos();
        alunos.setVisible(true);
    }//GEN-LAST:event_miAlunosActionPerformed

    private void miTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTreinosActionPerformed
        Treinos treinos = new Treinos();
        treinos.setVisible(true);
    }//GEN-LAST:event_miTreinosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAluno;
    private javax.swing.JButton btnTreino;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miAlunos;
    private javax.swing.JMenuItem miTreinos;
    private javax.swing.JMenu mnAluno;
    private javax.swing.JMenu mnTreino;
    // End of variables declaration//GEN-END:variables
}
